# Generated by Django 4.0.3 on 2022-03-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('new_face_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Faces',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='name_of_person',
        ),
    ]
