# Generated by Django 4.0.3 on 2022-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0002_newface_rename_faces_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newface',
            name='new_face_img',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
