# Generated by Django 4.0.3 on 2022-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0003_alter_newface_new_face_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newface',
            name='new_face_img',
            field=models.ImageField(upload_to='', verbose_name='media/'),
        ),
    ]
