# Generated by Django 4.0.3 on 2022-03-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0004_alter_newface_new_face_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewFace',
        ),
    ]
