# Generated by Django 4.0.3 on 2022-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0005_delete_newface'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
