# Generated by Django 4.0.3 on 2022-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0007_myimage_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
