# Generated by Django 4.0.3 on 2022-03-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0008_myimage_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myImage',
        ),
    ]
