# Generated by Django 4.0.3 on 2022-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionApp', '0009_delete_myimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_rec_api/recognitionApp/static/new_face')),
            ],
        ),
    ]
